export const metadata = {
  title: 'Store',
  description: 'Generated by Next.js',
};
export default function StoreLayout({ children }) {
  return (
    <>
      <nav>
        <h3>Seccion store</h3>
        <ul>
          <li>Category</li>
          <li>Products</li>
        </ul>
      </nav>
      {children}
    </>
  );
}
