import React from 'react';

export const metadata = {
  title: 'Store',
  description: 'Generated by Next.js',
};
export default function StoreLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>
        <h3>Seccion store</h3>
        <ul>
          <li>Category</li>
          <li>Products</li>
        </ul>
      </nav>
      {children}
    </>
  );
}
